title:              Haoran Bai
email:              hrbai.cs@gmail.com
description:        Welcome to my homepage~
author:             Haoran Bai
baseurl:            "/homepage"
url:                "https://baihaoran.xyz/"

# Social Profiles
twitter_username:
github_username:    csbhr
facebook_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
